Controllers/EventController.cs
using System;
using CSGO_Event_Recorder.Model;
using Microsoft.AspNetCore.Mvc;

namespace CSGO_Event_Recorder.Controllers
{
    public class EventController : Controller
    {
        public IActionResult Index(int id)
        {
            ViewBag.CurrentEvent = DBConnector.Instance.SelectEventFromId(id);
            ViewBag.TeamsInCurrentEvent = DBConnector.Instance.SelectAllTeamsFromEventId(id);
            return View("Index");
        }

        public IActionResult New()
        {
            ViewBag.AllOrganizer = DBConnector.Instance.SelectAllOranizer();
            return View("New");
        }

        public IActionResult NewGame(int eventId)
        {
            ViewBag.AllMaps = DBConnector.Instance.SelectAllMaps();
            ViewBag.AllTeams = DBConnector.Instance.SelectAllTeams();
            ViewBag.CurrentEvent = eventId;
            return View("NewGame");
        }

        public IActionResult Game(int map, int team1, int team2, int eventId)
        {
            if(team1 == team2)
            {
                ViewBag.Message = "No 2 Teams";
                return NewGame(eventId);
            }
            ViewBag.Message = null;
            ViewBag.CurrentMap = DBConnector.Instance.SelectMapFromId(map);
            ViewBag.Team1 = DBConnector.Instance.SelectTeamFromId(team1);
            ViewBag.Team2 = DBConnector.Instance.SelectTeamFromId(team2);
            ViewBag.CurrentEvent = eventId;
            
            return View();
        }

        public IActionResult FinishGame(int eventId, int mapId, int team1Id, int team2Id, int scoreTeam1, int scoreTeam2,
            int team1attckedA, int team1attackedB, int team1attackedAsuccess, int team1attckedBsuccess,
            int team1retakeA, int team1retakeB, int team2attckedA, int team2attackedB, 
            int team2attackedAsuccess, int team2attckedBsuccess, int team2retakeA, int team2retakeB)
        {
            var match = new Match()
            {
                Map = mapId,
                Team1 = team1Id,
                Team2 = team2Id,
                Team1Score = scoreTeam1,
                Team2Score = scoreTeam2,
                Team1AttackedA = team1attckedA,
                Team1AttackedB = team1attackedB,
                Team1AttackedASuccess = team1attackedAsuccess,
                Team1AttackedBSuccess = team1attckedBsuccess,
                Team1RetakeASuccess = team1retakeA,
                Team1RetakeBSuccess = team1retakeB,
                Team2AttackedA = team2attckedA,
                Team2AttackedB = team2attackedB,
                Team2AttackedASuccess = team2attackedAsuccess,
                Team2AttackedBSuccess = team2attckedBsuccess,
                Team2RetakeASuccess = team2retakeA,
                Team2RetakeBSuccess = team2retakeB
            };
            DBConnector.Instance.InsertNewmatch(match);
            
            return Index(eventId);
        }

        public IActionResult Add(string name, string date, string venue, string organizer)
        {
            if(!string.IsNullOrEmpty(name) && !string.IsNullOrEmpty(date) && !string.IsNullOrEmpty(venue) )
            {
                DBConnector.Instance.InsertEvent(new Event(){
                    Id = DBConnector.Instance.SelectAllEvents().Count + 1,
                    Name = name,
                    Date = date,
                    Venue = venue,
                    OrganizerID = Convert.ToInt32(organizer),
                    Organizer = DBConnector.Instance.SelectOrganizerFromId(Convert.ToInt32(organizer))
                });

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Message = "ForgotSomething";
                return New();
            }
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CSGO_Event_Recorder.Model;
using Microsoft.AspNetCore.Mvc;

namespace CSGO_Event_Recorder.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.AllEvents = DBConnector.Instance.SelectAllEvents();
            return View();
        }
    }
}

Controllers/TeamController.cs
using System.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CSGO_Event_Recorder.Model;
using Microsoft.AspNetCore.Mvc;

namespace CSGO_Event_Recorder.Controllers
{
    public class TeamController : Controller
    {
        public IActionResult NewToEvent(int id)
        {
            ViewBag.CurrentEventId = id;
            ViewBag.TeamsNotAttending = new List<Team>();
            List<Team> teamsInEvent = DBConnector.Instance.SelectAllTeamsFromEventId(id);
            List<Team> allTeams = DBConnector.Instance.SelectAllTeams();
            
            ViewBag.TeamsNotAttending = allTeams.Where(t => !teamsInEvent.Any(t2 => t2.Id == t.Id)).ToList();

            return View();
        }

        public IActionResult AddToEvent(int teamId, int eventId)
        {
            DBConnector.Instance.InsertTeamToEvent(teamId, eventId);

            return Redirect("/Event/?Id=" + eventId);
        }

        public IActionResult Details(int id)
        {
            ViewBag.TeamDetail = DBConnector.Instance.SelectTeamFromId(id);
            var allMaps = DBConnector.Instance.SelectAllMaps().ToArray();
            int[,] mapsInfo = new int[allMaps.Count(), 6];

            for(var i = 0; i < allMaps.Length; i++)
            {
                mapsInfo[i,0] = DBConnector.Instance.SelectAttackedOnA(id, allMaps[i].Id);
                mapsInfo[i,1] = DBConnector.Instance.SelectAttackedOnASuccess(id, allMaps[i].Id);
                mapsInfo[i,2] = DBConnector.Instance.SelectAttackedOnB(id, allMaps[i].Id);
                mapsInfo[i,3] = DBConnector.Instance.SelectAttackedOnBSuccess(id, allMaps[i].Id);
                mapsInfo[i,4] = DBConnector.Instance.SelectRetakeOnASuccess(id, allMaps[i].Id);
                mapsInfo[i,5] = DBConnector.Instance.SelectRetakeOnBSuccess(id, allMaps[i].Id);
            }

            ViewBag.AllMaps = allMaps;
            ViewBag.MapsInfo = mapsInfo;

            return View();
        }

        public IActionResult Statistics()
        {
            ViewBag.Statistics = DBConnector.Instance.SelectAllStatistics();
            return View();
        }

        public IActionResult UpdateAllStatistics()
        {
            return Json(DBConnector.Instance.SelectAllStatistics());
        }

        public IActionResult UpdateStatistics(string name)
        {
            return Json(DBConnector.Instance.SelectStatisticsFromName(name));
        }
    }
}

Views/Event/Game.cshtml
@{
    Layout = null;
    var team1 = ViewBag.Team1;
    var team2 = ViewBag.Team2;
    var map = ViewBag.CurrentMap;
}
<html>
<head>
    <title>New Game</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/darkly/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-S7YMK1xjUjSpEnF4P8hPUcgjXYLZKK3fQW1j5ObLSl787II9p8RO9XUGehRmKsxd" crossorigin="anonymous">
    <script src="@Url.Content("~/js/game.js")"></script>
</head>
<body>
    <div id="content" class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1>Game between @team1.Name and @team2.Name on @map.Name</h1>
                <h3 id="score">Score: 0 - 0</h3>
                @using(Html.BeginForm("FinishGame", "Event", FormMethod.Post, new { @class="form-horizontal" }))
                {
                    <div class="col-lg-6">
                        <div class="panel panel-warning">
                            <div class="panel-heading">
                                <h3 class="panel-title">@team1.Name</h3>
                            </div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <div class="input-group">
                                        <span class="input-group-addon">Attacked A site:</span>
                                        <input type="text" id="team1attckedA" name="team1attckedA" value="0" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" onclick="increaseValue('team1attckedA')" type="button">Add</button>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                    <span class="input-group-addon">Attacked B site:</span>
                                        <input type="text" id="team1attackedB" name="team1attackedB" value="0" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" onclick="increaseValue('team1attackedB')" type="button">Add</button>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                    <span class="input-group-addon">Attacked successfully A site:</span>
                                        <input type="text" id="team1attackedAsuccess" name="team1attackedAsuccess" value="0" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" onclick="increaseValue('team1attackedAsuccess')" type="button">Add</button>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                    <span class="input-group-addon">Attacked successfully B site:</span>
                                        <input type="text" id="team1attckedBsuccess" name="team1attckedBsuccess" value="0" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" onclick="increaseValue('team1attckedBsuccess')" type="button">Add</button>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                    <span class="input-group-addon">Retake A site:</span>
                                        <input type="text" id="team1retakeA" name="team1retakeA" value="0" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" onclick="increaseValue('team1retakeA')" type="button">Add</button>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                    <span class="input-group-addon">Retake B site:</span>
                                        <input type="text" id="team1retakeB" name="team1retakeB" value="0" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" onclick="increaseValue('team1retakeB')" type="button">Add</button>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="panel panel-warning">
                            <div class="panel-heading">
                                <h3 class="panel-title">@team2.Name</h3>
                            </div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <div class="input-group">
                                        <span class="input-group-addon">Attacked A site:</span>
                                        <input type="text" id="team2attckedA" name="team2attckedA" value="0" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" onclick="increaseValue('team2attckedA')" type="button">Add</button>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                    <span class="input-group-addon">Attacked B site:</span>
                                        <input type="text" id="team2attackedB" name="team2attackedB" value="0" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" onclick="increaseValue('team2attackedB')" type="button">Add</button>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                    <span class="input-group-addon">Attacked successfully A site:</span>
                                        <input type="text" id="team2attackedAsuccess" name="team2attackedAsuccess" value="0" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" onclick="increaseValue('team2attackedAsuccess')" type="button">Add</button>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                    <span class="input-group-addon">Attacked successfully B site:</span>
                                        <input type="text" id="team2attckedBsuccess" name="team2attckedBsuccess" value="0" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" onclick="increaseValue('team2attckedBsuccess')" type="button">Add</button>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                    <span class="input-group-addon">Retake A site:</span>
                                        <input type="text" id="team2retakeA" name="team2retakeA" value="0" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" onclick="increaseValue('team2retakeA')" type="button">Add</button>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                    <span class="input-group-addon">Retake B site:</span>
                                        <input type="text" id="team2retakeB" name="team2retakeB" value="0" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" onclick="increaseValue('team2retakeB')" type="button">Add</button>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <input name="eventId" value="@ViewBag.CurrentEvent" hidden>
                            <input id="scoreTeam1" name="scoreTeam1" value="0" hidden>
                            <input id="scoreTeam2" name="scoreTeam2" value="0" hidden>
                            <input name="team1Id" value="@team1.Id" hidden>
                            <input name="team2Id" value="@team2.Id" hidden>
                            <input name="mapId" value="@map.Id" hidden>
                            <button type="reset" class="btn btn-default">Cancel</button>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</body>
</html>

Views/Event/Index.cshtml
@{
    Layout = null;
    string imgStyle = "height: 242, width: 200";
}
<html>
<head>
    <title>Event Overview</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/darkly/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-S7YMK1xjUjSpEnF4P8hPUcgjXYLZKK3fQW1j5ObLSl787II9p8RO9XUGehRmKsxd" crossorigin="anonymous">
</head>
<body>
    <div id="content" class="container">
        <div class="row">
            <div class="col-lg-12">
                @if(ViewBag.CurrentEvent != null)
                {
                    <h1>@ViewBag.CurrentEvent.Name Overview</h1>
                    <div class="col-lg-4">
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-info">Date: @ViewBag.CurrentEvent.Date</li>
                            <li class="list-group-item list-group-item-info">Venue: @ViewBag.CurrentEvent.Venue</li>
                            <li class="list-group-item list-group-item-info">Organizer: @ViewBag.CurrentEvent.Organizer.Name</li>
                        </ul>
                    </div>
                    <div class="col-lg-12" style="margin-bottom:10px">
                        <a href="/Event/NewGame?eventId=@ViewBag.CurrentEvent.Id" class="btn btn-primary btn-lg btn-block">New Game</a>
                    </div>
                    <div class="col-lg-12">
                        @foreach(var t in ViewBag.TeamsInCurrentEvent)
                        {
                            <div class="col-sm-7 col-md-4">
                                <div class="thumbnail">
                                    <img style=@imgStyle src=@t.Logo />
                                    <div class="caption">
                                        <h3>@t.Name</h3>
                                        <p>Country: @t.Country</p>
                                        <p><a href="/Team/Details?id=@t.Id" class="btn btn-success center-block" role="button">Details</a></p>
                                    </div>
                                </div>
                            </div>
                        }
                        <div class="col-sm-7 col-md-4">
                            <div class="thumbnail">
                                <img style=@imgStyle src="http://iconshow.me/media/images/Mixed/Free-Flat-UI-Icons/png/512/plus-24-512.png" />
                                <div class="caption">
                                    <p><a href="/Team/NewToEvent?Id=@ViewBag.CurrentEvent.Id" class="btn btn-success center-block" role="button">Add Team</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</body>
</html>

Views/Event/New.cshtml
@{
    Layout = null;
}
<html>
<head>
    <title>New Event</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/darkly/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-S7YMK1xjUjSpEnF4P8hPUcgjXYLZKK3fQW1j5ObLSl787II9p8RO9XUGehRmKsxd" crossorigin="anonymous">
</head>
<body>
    <div id="content" class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1>Create a new Event</h1>
                @if(ViewBag.Message != null)
                {
                    <div class="alert alert-dismissible alert-danger">
                        <strong>Oh snap!</strong> <p>It seems you forgot something</p>
                    </div>
                }
                <div class="well bs-component">
                    @using(Html.BeginForm("Add", "Event", FormMethod.Post, new { @class="form-horizontal" }))
                    {
                        <fieldset>
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Name</label>
                                <div class="col-lg-10">
                                    <input 
                                        type="text" 
                                        class="form-control" 
                                        placeholder="Name"
                                        name="name"
                                    />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Date</label>
                                <div class="col-lg-10">
                                    <input type="date" 
                                        class="form-control" 
                                        placeholder="Date" 
                                        name="date"
                                        />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Venue</label>
                                <div class="col-lg-10">
                                    <input 
                                        type="text" 
                                        class="form-control" 
                                        placeholder="Venue" 
                                        name="venue"
                                    />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Organizer</label>
                                <div class="col-lg-10">
                                @if(ViewBag.AllOrganizer != null)
                                {
                                    <select class="form-control" name="organizer">
                                            @foreach(var o in ViewBag.AllOrganizer)
                                            {
                                                <option value=@o.Id>@o.Name</option>
                                            }
                                        
                                    </select>
                                }
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-10 col-lg-offset-2">
                                    <button type="submit" class="btn btn-primary center-block">Submit</button>
                                </div>
                            </div>
                        </fieldset>
                    }
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Views/Event/NewGame.cshtml
@{
    Layout = null;
}
<html>
<head>
    <title>New Game</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/darkly/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-S7YMK1xjUjSpEnF4P8hPUcgjXYLZKK3fQW1j5ObLSl787II9p8RO9XUGehRmKsxd" crossorigin="anonymous">
</head>
<body>
    <div id="content" class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1>Create a new Game</h1>
                @if(ViewBag.Message != null)
                {
                    <div class="alert alert-dismissible alert-danger">
                        <strong>Oh snap!</strong> <p>The same team cannot play against itself.</p>
                    </div>
                }
                <div class="well bs-component">
                    @using(Html.BeginForm("Game", "Event", FormMethod.Post, new { @class="form-horizontal" }))
                    {
                        <div class="form-group">
                            <label class="col-lg-2 control-label">Map</label>
                            <div class="col-lg-10">
                                @if(ViewBag.AllMaps != null)
                                {
                                    <select class="form-control" name="map">
                                        @foreach(var m in ViewBag.AllMaps)
                                        {
                                            <option value=@m.Id>@m.Name</option>
                                        }
                                    </select>
                                }
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-2 control-label">Team 1</label>
                            <div class="col-lg-10">
                                @if(ViewBag.AllTeams != null)
                                {
                                    <select class="form-control" name="team2">
                                        @foreach(var t in ViewBag.AllTeams)
                                        {
                                            <option value=@t.Id>@t.Name</option>
                                        }
                                    </select>
                                }
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-2 control-label">Team 2</label>
                            <div class="col-lg-10">
                                @if(ViewBag.AllTeams != null)
                                {
                                    <select class="form-control" name="team1">
                                        @foreach(var t in ViewBag.AllTeams)
                                        {
                                            <option value=@t.Id>@t.Name</option>
                                        }
                                    </select>
                                }
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-10 col-lg-offset-2">
                                <input name="eventId" value="@ViewBag.CurrentEvent" hidden>
                                <button type="submit" class="btn btn-primary center-block">Submit</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Views/Home/Index.cshtml
@{
    Layout = null;
    string imgStyle = "height: 242, width: 200";
}
<html>
<head>
    <title>Event Recorder</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/darkly/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-S7YMK1xjUjSpEnF4P8hPUcgjXYLZKK3fQW1j5ObLSl787II9p8RO9XUGehRmKsxd" crossorigin="anonymous">
</head>
<body>
    <div id="content" class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-header">
                    <h1 id="typography">Counter Strinke: Global Offensive Event Counter</h1>
                </div>
                @if(ViewBag.AllEvents != null)
                {
                    @foreach (var e in ViewBag.AllEvents)
                    {
                        <div class="col-sm-7 col-md-3">
                            <div class="thumbnail">
                                <img style=@imgStyle src=@e.Organizer.Logo />
                                <div class="caption">
                                    <h3>@e.Name</h3>
                                    <p>Venue: @e.Venue</p>
                                    <p>Date: @e.Date</p>
                                    <p>Organizer: @e.Organizer.Name</p>
                                    <p><a href="/event/?id=@e.Id" class="btn btn-success center-block" role="button">Choose</a></p>
                                </div>
                            </div>
                        </div>
                    }
                }
                <div class="col-sm-7 col-md-3">
                    <div class="thumbnail">
                        <img style=@imgStyle 
                            src="http://iconshow.me/media/images/Mixed/Free-Flat-UI-Icons/png/512/plus-24-512.png"
                        />
                        <div class="caption">
                            <p><a href="/event/new" class="btn btn-success center-block" role="button">New Event</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <a href="/Team/Statistics" class="btn btn-primary btn-lg btn-block">Show Team Statistics</a>
            </div>
        </div>
    </div>
</body>
</html>